before:
  hooks:
    - go mod tidy

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    binary: dfe-attendance
    ldflags:
      - -s -w -X github.com/lukecarr/dfe-attendance/internal/info.Version={{.Tag}} -X github.com/lukecarr/dfe-attendance/internal/info.Commit={{.FullCommit}} -X github.com/lukecarr/dfe-attendance/internal/info.Date={{.Date}}
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: macos
      "386": 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
